### ISSUE TITLE
Support for 4K Version?

### ISSUE THREAD

**Issue by jonfairbanks** [modem7/docker-rickroll#2]
First off, great container... thank you. Any plans to support the upscaled version of the Rickroll video?

https://www.youtube.com/watch?v=bxqLsrlakK8

Thank you!

**Comment by modem7** [comment]
I wasn't even aware this version existed!

I'll see what I can do!

Thanks for letting me know!

The biggest constraint will be size. As the larger it is, the more delay there will be starting it. 

I'll see what size I can get the 4k one down to, worst case, I'll transcode it to 1080.

I found an extended version (https://youtu.be/o-YBDTqX_ZU) which I'd like to use, so watch this space!

**Comment by modem7** [comment]
@jonfairbanks Could you try the following tags for me please?

I've made two versions for you. One is a transcoded version of the 4k into 1080p, and one is the original quality.

modem7/docker-rickroll:1080
modem7/docker-rickroll:1080onclick
modem7/docker-rickroll:4k
modem7/docker-rickroll:4k-onclick

Let me know how you get on

**Comment by jonfairbanks** [comment]
Haha awesome!! Thanks for the quick turnaround! 4k/1080 versions work great.

For all onclick images (even previous ones), the video does not play for me on Firefox. The only way I was able to get that container to work was right click and hit play. 

![Screenshot_6](https://user-images.githubusercontent.com/1957806/130300148-058ed9f4-480f-4453-b319-30dd61864b05.png)

**Comment by modem7** [comment]
No worries! Glad it works!

Unfortunately Firefox is being a s**t with anything useful. Works nicely with anything chromium (Chrome, Vivaldi, Edge etc), but Firefox has some security nonsense that as a non-webdev, I honestly have no idea how to work past!

https://github.com/modem7/docker-rickroll/issues/1#issuecomment-900501438 mentions it, but until we get someone who can get it working, alas, no Firefox compatibility with onclick.

**Comment by jonfairbanks** [comment]
Ahhh gotcha, no concerns then. Thanks again for the new image!

**Comment by modem7** [comment]
I'll leave #1 open in case someone know how to resolve the Firefox issue

**Comment by diothar** [comment]
Hi, looks like I can't use the 4k tag any more. Is this still an option?

**Comment by modem7** [comment]
> Hi, looks like I can't use the 4k tag any more. Is this still an option?

Heya, 

Unfortunately not. The space required for the 4k version was above 50mb, which would mean I'd have to use git LFS, which is chargeable, and as I do this as a side hobby, it just wasn't worth it.

You can however, locally mount a file, overwriting the current rickroll.mp4 file with a 4k one.

**Comment by diothar** [comment]
Oh that's a bummer, but thanks for letting me know why.  
So I would take your docker image and just modify the source file location?

**Comment by modem7** [comment]
> Oh that's a bummer, but thanks for letting me know why. So I would take your docker image and just modify the source file location?

That's it!

Something like this should do it:

```
  rickroll:
    image: modem7/docker-rickroll
    container_name: Rickroll
    volumes:
      - /mnt/MYRICKROLL4K.mp4:/usr/share/nginx/html/rickroll.mp4
    ports:
      - 8080:8080
```
