### ISSUE TITLE
OnClick Image Quality

### ISSUE THREAD

**Issue by Surgical71** [modem7/docker-rickroll#38]
Can we maybe get a better image Quality for the OnClick to make it look a bit more real?

**Comment by modem7** [comment]
Have you tried the 1080onclick tag?

Or do you mean the click image itself?

**Comment by modem7** [comment]
@Surgical71 Unsure if you got this reply.

**Comment by modem7** [comment]
Closing as no reply + added an environment variable where you can define your own image in https://github.com/modem7/docker-rickroll/commit/2ff48743b408430f7f7362e5d36317255b1ce946.

@auridas330 - this may interest you as well.

**Comment by auridas330** [comment]
> Closing as no reply + added an environment variable where you can define your own image in [2ff4874](https://github.com/modem7/docker-rickroll/commit/2ff48743b408430f7f7362e5d36317255b1ce946).
> 
> @auridas330 - this may interest you as well.

@modem7  Wow, thanks! I did not wanna bother you with such a trivial issue, forking and editing one file seemed eaasier haha
