### ISSUE TITLE
Video offset, text-align: center; 

### ISSUE THREAD

**Issue by mechanicalfluff** [modem7/docker-rickroll#41]
When you change text-align to start, it fits normally
Not exactly sure why the layout suddenly changed - does it in chrome/edge/firefox

![image](https://user-images.githubusercontent.com/24421525/197067735-ec9dcd24-91e0-495c-8170-ee64c2e13130.png)

**Comment by modem7** [comment]
Heya,

I'll have a look at this. I recently updated the base image, so I wonder if it's something to do with this.

Worst case, I'll create a variable for it so it can be changed at will.

Does it happen with both thegame and onclick tags for you?

**Comment by mechanicalfluff** [comment]
yes it does. i use onclick but i tried all of them with the same result

**Comment by modem7** [comment]
Reopening as I need to investigate.

**Comment by modem7** [comment]
Looks like this was caused by https://github.com/modem7/docker-rickroll/pull/39 - have reverted the changes and will push out a new build.

**Comment by modem7** [comment]
Reverted changed, new build is now live. 

Confirmed working. Thanks for the report!
